% This test file was generated by Copilot. Validate the generated output before use.
classdef mat_ops_test < matlab.unittest.TestCase
    methods(Test)
        function testMatrixMultiplication(testCase)
            A = [1, 2; 3, 4];
            B = [5; 6];
            expectedC = [17; 39];

            actualC = mat_ops(A, '*', B);

            testCase.verifyEqual(actualC, expectedC);
        end

        function testMatrixLeftDivision(testCase)
            A = [1, 2; 3, 4];
            B = [5; 6];
            expectedC = [1; 2];

            actualC = mat_ops(A, '\', B);

            testCase.verifyEqual(actualC, expectedC);
        end

        function testMatrixRightDivision(testCase)
            A = [1, 2; 3, 4];
            B = [5, 6];
            expectedC = [0.44, 0.56; 0.88, 1.12];

            actualC = mat_ops(A, '/', B);

            testCase.verifyEqual(actualC, expectedC, 'AbsTol', 1e-2);
        end

        function testDimensionMismatchMultiplication(testCase)
            A = [1, 2; 3, 4];
            B = [5, 6, 7];

            testCase.verifyError(@() mat_ops(A, '*', B), 'MAT_OPS:dimensionMismatch');
        end

        function testDimensionMismatchLeftDivision(testCase)
            A = [1, 2; 3, 4];
            B = [5, 6];

            testCase.verifyError(@() mat_ops(A, '\', B), 'MAT_OPS:sizeMismatch');
        end

        function testDimensionMismatchRightDivision(testCase)
            A = [1, 2; 3, 4];
            B = [5; 6; 7];

            testCase.verifyError(@() mat_ops(A, '/', B), 'MAT_OPS:sizeMismatch');
        end
    end
end